erDiagram

  User {
    String id PK 
    String username  
    String hashedPassword  
    String accountId  
    }
  

  Account {
    String id PK 
    Int balance  
    }
  

  Transaction {
    String id PK 
    DateTime createdAt  
    Int value  
    String debitedAccountId  
    String creditedAccountId  
    }
  
    User o{--|| Account : "Account"
    Transaction o{--|| Account : "CreditedAccountId"
    Transaction o{--|| Account : "DebitedAccountId"
